#!/bin/sh
exec tail -n +3 $0

menuentry "Arch Linux" --class arch --class os {
    insmod part_gpt
    insmod fat
    insmod chain
    search --no-floppy --fs-uuid --set=root A794-BC84
    chainloader /EFI/Linux/arch-linux-zen.efi
}
