#!/bin/sh
exec tail -n +3 $0

menuentry "Windows 11" --class windows --class os {
    insmod part_gpt
    insmod fat
    search --no-floppy --fs-uuid --set=root 3CD3-1790
    chainloader /efi/Microsoft/Boot/bootmgfw.efi
}
